name       : plocate
version    : 1.1.15
release    : 3
source     :
    - https://plocate.sesse.net/download/plocate-1.1.15.tar.gz : d1855954da8b811887de0e12ed8d236c0599ecd959ec5a6851503315507bf150
license    : GPL-2.0-or-later
component  : system.utils
summary    : plocate, a much faster locate
description: |
    plocate is a locate based on posting lists, completely replacing mlocate with a much faster (and smaller) index. It is suitable as a default locate on your system.
replaces   :
    - mlocate
builddeps  :
    - pkgconfig(liburing)
    - pkgconfig(libzstd)
setup      : |
    # Things are setup here to overwrite the pre-existing findutils locate db.
    %patch -p1 < $pkgfiles/0001-Statelessness.patch
    %meson_configure \
        -Ddbpath=locate/locate.db \
        -Dlocategroup=locate \
        -Dinstall_systemd=true \
        -Dsharedstatedir=/var/db \
build      : |
    %ninja_build
install    : |
    %ninja_install

    chgrp 21 $installdir/usr/bin/plocate
    chmod 2755 $installdir/usr/bin/plocate

    # Strip plocate-build, not needed
    rm -fr $installdir/usr/sbin/plocate-build
    rm -fr $installdir/usr/share/man/man8

    install -Dm00644 $pkgfiles/plocate.tmpfiles $installdir/usr/lib64/tmpfiles.d/plocate.conf
    install -Dm00644 $pkgfiles/plocate.sysusers $installdir/usr/lib64/sysusers.d/plocate.conf
    install -Dm00644 $pkgfiles/updatedb.conf $installdir/usr/share/defaults/etc/updatedb.conf

    # Add legacy symlinks
    ln -sv plocate $installdir/usr/bin/locate
    ln -sv plocate $installdir/usr/bin/mlocate
